### PR TITLE
Validation branch

### PR DESCRIPTION
**Pull request by Lul-Abdifan**
In this PR we have done:-## In this PR we have done:-

   -Validate the contact form.
   - Return error message if the email is not written in lowercase.
   - Make error message around submit button
   - Update  Readme file

### CODE REVIEW

**Review by 1GORDON — CHANGES_REQUESTED** [review]
##
## Hi @Lul-Abdifan & @naolkidanu ✋

Good job so far!

## Highlights!
- Followed Gitflow ✔️ 
- Good commit messages ✔️
- Linters are passing ✔️
- Descriptive Pull request ✔️

Hello ✋, you have done well reaching this point of the milestone 🤝 . But there are some issues that you still need to work on to go to the next project but you are almost there!

# Status: Required Changes ♻️⛔️

- [ ] As stated in the project requirements, kindly make sure the error message displays near the submit button.
error-button


_Check the comments under the review._

## Optional suggestions

- [ ] Kindly use [markdown syntax](https://guides.github.com/features/mastering-markdown/) to format your Readme file efficiently. This will make your Readme file look more professional.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread and tag me `@1GORDON` if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by aimalamiri — APPROVED** [review]
Hi @Lul-Abdifan, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

ApprovedDavieGIF


## Highlights

- The validation functionality works very well and look fantastic ✔️ ⭐
- Good job for using the right GitHub Flow 💯
- Awesome file organization 🗃️
- Commits are descriptive and meaningful 👍
- Linters are properly set up and passing 🟢 👍

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lul-Abdifan** [comment]
[1GORDON](https://github.com/1GORDON) thank you brou.I will do on it. Happy coding.

**Comment by Lul-Abdifan** [comment]
***@***.***, Thank you. Happy Coding.*

**Comment by Lul-Abdifan** [comment]
@aimalamiri ,thank you.Happy coding.

**Pull request merged**
